FROM intersystems/iam:1.5.0.9-4

USER root
COPY ./plugins /custom/plugins

RUN cd /custom/plugins/kong-plugin-helloworld && luarocks make
RUN cd /custom/plugins/kong-plugin-jwt-crafter && luarocks make

USER kong

